/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SeedGenerator;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.Statement;

/**
 *
 * @author Semih
 */
public class FormConfirmation extends javax.swing.JFrame {

    public boolean confirmed = false;
    Connection con;

    /**
     * Creates new form FormConfirmation
     */
    public FormConfirmation(Connection con) {
        this.con = con;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfirm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtconfirm = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        lbltypeiamsure = new javax.swing.JLabel();

        btnConfirm.setText("Yes");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtconfirm);

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("This will reset all your database tables. Are you sure to perform this operation?");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lbltypeiamsure.setText("Type: \"I am sure!\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(11, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbltypeiamsure)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirm))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltypeiamsure)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnConfirm))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        if (txtconfirm.getText().equals("I am sure!")) {

            String s = new String();
            StringBuffer sb = new StringBuffer();

            try {
                FileReader fr = new FileReader(new File("db.sql"));

                BufferedReader br = new BufferedReader(fr);

                while ((s = br.readLine()) != null) {
                    if (!s.startsWith("--")) {
                        sb.append(s);
                    }
                }
                br.close();

                String[] stmts = sb.toString().split(";");

                for (int i = 0; i < stmts.length; i++) {
                    if (stmts[i].contains("BEGIN")) {
                        int tInt = i;
                        while (tInt < stmts.length && !stmts[tInt].contains("END")) {
                            tInt++;
                        }

                        stmts[i] += ";";

                        for (int j = (i + 1); j < tInt; j++) {
                            stmts[i] += "\n" + stmts[j] + ";";
                            stmts[j] = " ";
                        }
                        stmts[i] += "\nEND";

                        String tStr[] = stmts[tInt].split("END");
                        stmts[tInt] = tStr[1];
                        i = tInt - 1;
                    } //end if

                } //end for

                Statement st = con.createStatement();

                for (int i = 0; i < stmts.length; i++) {
                    if (!stmts[i].trim().equals("")) {
                        System.out.println(">>" + stmts[i]);
                        st.executeUpdate(stmts[i]);
                    }
                }
            } catch (Exception e) {
                System.out.println("*** Error : " + e.toString());
                System.out.println("*** ");
                System.out.println("*** Error : ");
                e.printStackTrace();
                System.out.println("################################################");
                System.out.println(sb.toString());
            }
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false);

    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbltypeiamsure;
    private javax.swing.JTextPane txtconfirm;
    // End of variables declaration//GEN-END:variables
}
